# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\vfxProject.ui'
#
# Created: Wed Apr 11 18:14:16 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1349, 961)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_TaskPanel = QtWidgets.QFrame(self.centralwidget)
        self.frame_TaskPanel.setGeometry(QtCore.QRect(520, 10, 811, 901))
        self.frame_TaskPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TaskPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TaskPanel.setObjectName("frame_TaskPanel")
        self.groupBox_DataTree = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_DataTree.setGeometry(QtCore.QRect(10, 46, 501, 865))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox_DataTree.setFont(font)
        self.groupBox_DataTree.setObjectName("groupBox_DataTree")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 501, 41))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 14, 491, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_resX = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_resX.setObjectName("label_resX")
        self.horizontalLayout.addWidget(self.label_resX)
        self.label_resY = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_resY.setObjectName("label_resY")
        self.horizontalLayout.addWidget(self.label_resY)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_fps = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_fps.setObjectName("label_fps")
        self.horizontalLayout.addWidget(self.label_fps)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1349, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Daily = QtWidgets.QAction(MainWindow)
        self.action_Daily.setObjectName("action_Daily")
        self.action_PackCache = QtWidgets.QAction(MainWindow)
        self.action_PackCache.setObjectName("action_PackCache")
        self.action_PackRenderSeq = QtWidgets.QAction(MainWindow)
        self.action_PackRenderSeq.setObjectName("action_PackRenderSeq")
        self.action_PackCompSeq = QtWidgets.QAction(MainWindow)
        self.action_PackCompSeq.setObjectName("action_PackCompSeq")
        self.action_Setting = QtWidgets.QAction(MainWindow)
        self.action_Setting.setObjectName("action_Setting")
        self.action_Fresh = QtWidgets.QAction(MainWindow)
        self.action_Fresh.setObjectName("action_Fresh")
        self.menu.addAction(self.action_Open)
        self.menu.addAction(self.action_New)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Setting)
        self.menu.addAction(self.action_Fresh)
        self.menu_2.addAction(self.action_Daily)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_PackCache)
        self.menu_2.addAction(self.action_PackRenderSeq)
        self.menu_2.addAction(self.action_PackCompSeq)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "VFXManager", None, -1))
        self.groupBox_DataTree.setTitle(QtWidgets.QApplication.translate("MainWindow", "Data Tree", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Project", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "分辨率", None, -1))
        self.label_resX.setText(QtWidgets.QApplication.translate("MainWindow", "resX", None, -1))
        self.label_resY.setText(QtWidgets.QApplication.translate("MainWindow", "resY", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "帧率", None, -1))
        self.label_fps.setText(QtWidgets.QApplication.translate("MainWindow", "fps", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "项目", None, -1))
        self.menu_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "功能", None, -1))
        self.action_Open.setText(QtWidgets.QApplication.translate("MainWindow", "打开", None, -1))
        self.action_New.setText(QtWidgets.QApplication.translate("MainWindow", "新建", None, -1))
        self.action_Daily.setText(QtWidgets.QApplication.translate("MainWindow", "发布Daily", None, -1))
        self.action_PackCache.setText(QtWidgets.QApplication.translate("MainWindow", "打包缓存", None, -1))
        self.action_PackRenderSeq.setText(QtWidgets.QApplication.translate("MainWindow", "打包渲染序列", None, -1))
        self.action_PackCompSeq.setText(QtWidgets.QApplication.translate("MainWindow", "打包合成序列", None, -1))
        self.action_Setting.setText(QtWidgets.QApplication.translate("MainWindow", "设置", None, -1))
        self.action_Fresh.setText(QtWidgets.QApplication.translate("MainWindow", "刷新", None, -1))

